"""add is_system to users

Revision ID: a16b9be7ea51
Revises: 0001
Create Date: 2026-04-21 11:49:36.827295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a16b9be7ea51'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invites', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('pokemon_forms', 'is_tradable',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('pokemon_forms', 'has_shiny',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index('ix_pokemon_forms_pokedex', table_name='pokemon_forms')
    op.drop_index('ix_pokemon_forms_pokemon_id', table_name='pokemon_forms')
    op.alter_column('user_flags', 'value',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('user_flags', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_user_flags_pokemon_form_id', table_name='user_flags')
    op.drop_index('ix_user_flags_user_id', table_name='user_flags')
    op.add_column('users', sa.Column('is_system', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('users', 'is_system')
    op.create_index('ix_user_flags_user_id', 'user_flags', ['user_id'], unique=False)
    op.create_index('ix_user_flags_pokemon_form_id', 'user_flags', ['pokemon_form_id'], unique=False)
    op.alter_column('user_flags', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_flags', 'value',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_index('ix_pokemon_forms_pokemon_id', 'pokemon_forms', ['pokemon_id'], unique=False)
    op.create_index('ix_pokemon_forms_pokedex', 'pokemon_forms', ['pokedex_number'], unique=False)
    op.alter_column('pokemon_forms', 'has_shiny',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('pokemon_forms', 'is_tradable',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('invites', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
